version: '3.7'

services:
  currency-exchange:
    image: mateuszkrolik/microservices-currency-exchange-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - currency-network

networks:
  currency-network: