version: '3.7'

services:
  currency-exchange:
    image: mateuszkrolik/microservices-currency-exchange-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  currency-conversion:
    image: mateuszkrolik/microservices-currency-conversion-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "8100:8100"
    env_file:
      - .env
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411

  api-gateway:
    image: mateuszkrolik/microservices-api-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "8765:8765"
    env_file:
      - .env
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411

  naming-server:
    image: mateuszkrolik/microservices-naming-server:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "8761:8761"
    env_file:
      - .env
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 500m
    ports:
      - "9411:9411"
    networks:
      - currency-network

networks:
  currency-network: