apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  dbHostname: {{ .Values.secret.dbHostname | b64enc }}
  dbPort: {{ .Values.secret.dbPort | b64enc }}
  dbName: {{ .Values.secret.dbName | b64enc }}
  dbUsername: {{ .Values.secret.dbUsername | b64enc }}
  dbPassword: {{ .Values.secret.dbPassword | b64enc }}