replicaCount: 1

image:
  pullPolicy: IfNotPresent
  currencyExchange:
    repository: mateuszkrolik/microservices-currency-exchange-service
    tag: "0.0.1-SNAPSHOT"
  currencyConversion:
    repository: currency-conversion-service
    tag: "local"

service:
  currencyExchange:
    type: ClusterIP
    port: 8000
  currencyConversion:
    type: ClusterIP
    port: 8100

ingress:
  className: nginx
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: currency.local
      paths:
        - path: /currency-exchange
          pathType: ImplementationSpecific
        - path: /currency-conversion-feign
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - currency.local
      secretName: currency-ingress-tls

configmap:
  currencyExchangeUri: "http://currency-services-currency-exchange"

secret:
  dbHostname: "postgres.database.svc.cluster.local"
  dbPort: "5432"
  dbName: "currency_exchange"
  dbUsername: "postgres"
  dbPassword: "mysecretpassword"

autoscaling:
  currencyExchange:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50